name: vqa_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - transformers
  - nltk
  - datasets=2.16.0
  - pillow
  - pytorch
  - torchvision
  - scikit-learn
  - pip
  - pip:
      - safetensors
